### ISSUE TITLE
Proxying not working with vhost

### ISSUE THREAD

**Issue by biegl** [drewzboto/grunt-connect-proxy#14]
First of all: You r awesome.

I am trying to proxy ajax calls from localhost:9000 to 'example.dev:80'. 
Example.dev is a local apache instance.

proxies: [
        {
          context: '/api',
          host: example.dev',
          port: 80
        }
      ],

From the apache log files I see that apache is always trying to load the document root (localhost).

**Comment by patrickallaert** [comment]
@HriBB Yes, grunt-connect-proxy should be able to change the "Host" header of the request to match the destination. This used to be supported with the `changeOrigin` option but support has been dropped apparently in version 0.1.11 (b468057991730da42dea4359008c6c109798914a).

The real problem is that changeOrigin should be true by default in _http-proxy_ package (you may +1 my issue here: https://github.com/nodejitsu/node-http-proxy/issues/1132).

The consequences of this is that if you proxy is on foobar.com and is redirecting requests to bargee.net, the `Host` header is still set on `foobar.com` which is plain wrong (according to HTTP 1.1 specs).

VirtualHost mechanism **solely** relies on the `Host` header. When a client connects a web server, it is using the ip/port combination, not the name of the server, this has to be injected in the `Host` header.

If no VirtualHost are found to match the `Host` header, then the first VirtualHost is used (in the case of Apache).
